INSERT INTO eos.departamento (IDDEPARTAMENTO, NOMBRE) VALUES (1, 'COCHABAMBA');
INSERT INTO eos.departamento (IDDEPARTAMENTO, NOMBRE) VALUES (2, 'SANTA CRUZ');
INSERT INTO eos.departamento (IDDEPARTAMENTO, NOMBRE) VALUES (3, 'LA PAZ');
INSERT INTO eos.departamento (IDDEPARTAMENTO, NOMBRE) VALUES (4, 'SUCRE');
INSERT INTO eos.departamento (IDDEPARTAMENTO, NOMBRE) VALUES (5, 'ORURO');
INSERT INTO eos.departamento (IDDEPARTAMENTO, NOMBRE) VALUES (6, 'BENI');
INSERT INTO eos.departamento (IDDEPARTAMENTO, NOMBRE) VALUES (7, 'PANDO');
INSERT INTO eos.departamento (IDDEPARTAMENTO, NOMBRE) VALUES (8, 'POTOSI');
INSERT INTO eos.departamento (IDDEPARTAMENTO, NOMBRE) VALUES (9, 'CHUQUISACA');
