/*
SQLyog Ultimate v11.11 (64 bit)
MySQL - 5.6.23-log 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `inv_articulos` (
	`À_o` varchar (6),
	`` varchar (18),
	`@`o` varchar (765),
	` `o` Decimal (12),
	`ð`o` varchar (9),
	`0ao` varchar (18),
	`€ao` Decimal (18),
	`Ðao` Decimal (18),
	` bo` Decimal (18),
	`pbo` varchar (300),
	`°bo` varchar (42),
	`` varchar (93),
	`Pco` varchar (765),
	` co` varchar (9),
	`àco` varchar (9),
	` do` Decimal (18),
	`pdo` varchar (18),
	`°do` bigint (20)
); 
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','156',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOGURT SACHET DURAZNO 140 CC',NULL,'40301001001001','N','VIG','3','1.000000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','155',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOGURT SACHET DURAZNO 150 CC',NULL,'40301001001001','N','VIG','3','1.000000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','154',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOGURT SACHET DURAZNO 120 CC',NULL,'40301001001001','N','VIG','3','1.000000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','157',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOGURT SACHET COCO 120 CC',NULL,'40301001001001','N','VIG','3','1.000000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','158',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOGURT SACHET COCO 140 CC',NULL,'40301001001001','N','VIG','3','1.000000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','159',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOGURT SACHET COCO 150 CC',NULL,'40301001001001','N','VIG','3','1.000000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','160',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOGURT SACHET COCO 500 CC',NULL,'40301001001001','N','VIG','3','1.000000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','153',NULL,NULL,'1',NULL,NULL,NULL,NULL,'YOGURT_BASE',NULL,'40302001001001','N','VIG','1','1.000000','LT','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','161',NULL,NULL,'4',NULL,NULL,NULL,NULL,'CHICOTRON 950 ML',NULL,'40301001001001','N','VIG','2','3.490000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','2',NULL,NULL,'2',NULL,NULL,NULL,NULL,'ACIDO CITRICO',NULL,'40302002001008','N','VIG','1','11.710000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','3',NULL,NULL,'2',NULL,NULL,NULL,NULL,'ESENCIA AVENA AROMCOLOR IL 581',NULL,'40302002001002','N','VIG','2','244.210000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','4',NULL,NULL,'2',NULL,NULL,NULL,NULL,'ESENCIA BANANA',NULL,'40302002001002','N','VIG','2','0.210000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','5',NULL,NULL,'2',NULL,NULL,NULL,NULL,'ESENCIA CANELA',NULL,'40302002001002','N','VIG','2','0.090000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','6',NULL,NULL,'2',NULL,NULL,NULL,NULL,'ESENCIA CAPUCHINO',NULL,'40302002001002','N','VIG','2','0.110000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','7',NULL,NULL,'2',NULL,NULL,NULL,NULL,'ESENCIA CHOCOLATE ',NULL,'40302002001002','N','VIG','2','0.150000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','8',NULL,NULL,'2',NULL,NULL,NULL,NULL,'ESENCIA COCO',NULL,'40302002001002','N','VIG','2','0.150000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','9',NULL,NULL,'2',NULL,NULL,NULL,NULL,'ESENCIA CREMA',NULL,'40302002001002','N','VIG','2','284.590000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','10',NULL,NULL,'2',NULL,NULL,NULL,NULL,'ESENCIA DAMAZCO',NULL,'40302002001002','N','VIG','2','0.290000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','11',NULL,NULL,'2',NULL,NULL,NULL,NULL,'ESENCIA DULCE DE LECHE',NULL,'40302002001002','N','VIG','2','123.540000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','12',NULL,NULL,'2',NULL,NULL,NULL,NULL,'ESENCIA DURAZNO',NULL,'40302002001002','N','VIG','2','0.120000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','13',NULL,NULL,'2',NULL,NULL,NULL,NULL,'ESENCIA FRUTILLA',NULL,'40302002001002','N','VIG','2','0.140000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','14',NULL,NULL,'2',NULL,NULL,NULL,NULL,'ESENCIA MANZANA',NULL,'40302002001002','N','VIG','2','0.200000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','15',NULL,NULL,'2',NULL,NULL,NULL,NULL,'ESENCIA MORA',NULL,'40302002001002','N','VIG','2','0.130000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','16',NULL,NULL,'2',NULL,NULL,NULL,NULL,'ESENCIA PIÃ‘A',NULL,'40302002001002','N','VIG','2','0.170000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','17',NULL,NULL,'2',NULL,NULL,NULL,NULL,'ESENCIA VAINILLA',NULL,'40302002001002','N','VIG','2','0.210000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','18',NULL,NULL,'2',NULL,NULL,NULL,NULL,'SABORIZANTE CHIRIMOYA TC-967',NULL,'40302002001002','N','VIG','2','187.450000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','19',NULL,NULL,'2',NULL,NULL,NULL,NULL,'SABORIZANTE COCO TC-965',NULL,'40302002001002','N','VIG','2','156.600000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','20',NULL,NULL,'2',NULL,NULL,NULL,NULL,'SABORIZANTE VAINIBUTT',NULL,'40302002001002','N','VIG','2','418.190000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','21',NULL,NULL,'2',NULL,NULL,NULL,NULL,'FERMENTO PARA QUESO',NULL,'40302002001006','N','VIG','3','61.790000','SB','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','22',NULL,NULL,'2',NULL,NULL,NULL,NULL,'FERMENTO PARA YOGURT',NULL,'40302002001006','N','VIG','3','6.160000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','23',NULL,NULL,'2',NULL,NULL,NULL,NULL,'FERMENTO PROBIOTICO',NULL,'40302002001006','N','VIG','3','4314.600000','SB','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','24',NULL,NULL,'2',NULL,NULL,NULL,NULL,'PULPA DE  FRUTILLA',NULL,'40302002001007','N','VIG','4','16.940000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','25',NULL,NULL,'2',NULL,NULL,NULL,NULL,'PULPA DE DURAZNO',NULL,'40302002001007','N','VIG','4','16.960000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','26',NULL,NULL,'2',NULL,NULL,NULL,NULL,'PULPA DE MANZANA',NULL,'40302002001007','N','VIG','4','16.960000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','27',NULL,NULL,'2',NULL,NULL,NULL,NULL,'PULPA DE NARANJA',NULL,'40302002001007','N','VIG','4','16.960000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','28',NULL,NULL,'2',NULL,NULL,NULL,NULL,'SAL',NULL,'40302002001017','N','VIG','5','0.830000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','29',NULL,NULL,'2',NULL,NULL,NULL,NULL,'CITRATO DE SODIO',NULL,'40302002001008','N','VIG','6','13.010000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','30',NULL,NULL,'2',NULL,NULL,NULL,NULL,'CITRUS PUNCH NARANJA',NULL,'40302002001008','N','VIG','7','199.010000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','31',NULL,NULL,'2',NULL,NULL,NULL,NULL,'CACAO ALCALINO T-150',NULL,'40302002001005','N','VIG','8','53.070000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','32',NULL,NULL,'2',NULL,NULL,NULL,NULL,'COCOA ALKALINA T-100',NULL,'40302002001005','N','VIG','8','53.070000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','33',NULL,NULL,'2',NULL,NULL,NULL,NULL,'MALTODEXTRINA',NULL,'40302002001016','N','VIG','9','9.250000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','34',NULL,NULL,'2',NULL,NULL,NULL,NULL,'CLORURO DE CALCIO',NULL,'40302002001017','N','VIG','10','6.520000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','35',NULL,NULL,'2',NULL,NULL,NULL,NULL,'AZUCAR',NULL,'40302002001001','N','VIG','11','3.740000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','36',NULL,NULL,'2',NULL,NULL,NULL,NULL,'BEKAPLUS Y3',NULL,'40302002001017','N','VIG','12','77.200000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','37',NULL,NULL,'2',NULL,NULL,NULL,NULL,'CMC ESTABILIZANTE',NULL,'40302002001017','N','VIG','12','0.050000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','38',NULL,NULL,'2',NULL,NULL,NULL,NULL,'EMULSIFICANTE ACIDMILK 374',NULL,'40302002001017','N','VIG','12','102.660000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','39',NULL,NULL,'2',NULL,NULL,NULL,NULL,'JOHA S-9',NULL,'40302002001017','N','VIG','12','87.800000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','40',NULL,NULL,'2',NULL,NULL,NULL,NULL,'PALSGARD 5820',NULL,'40302002001017','N','VIG','12','67.310000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','41',NULL,NULL,'2',NULL,NULL,NULL,NULL,'BENSOATO DE SODIO',NULL,'40302002001017','N','VIG','13','0.020000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','42',NULL,NULL,'2',NULL,NULL,NULL,NULL,'CONSERVANTE NATACID',NULL,'40302002001017','N','VIG','13','1.620000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','43',NULL,NULL,'2',NULL,NULL,NULL,NULL,'LISOZINA',NULL,'40302002001017','N','VIG','13','1574.700000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','44',NULL,NULL,'2',NULL,NULL,NULL,NULL,'NISINA',NULL,'40302002001012','N','VIG','13','2.940000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','45',NULL,NULL,'2',NULL,NULL,NULL,NULL,'NITRATO DE POTASIO',NULL,'40302002001017','N','VIG','13','18.350000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','46',NULL,NULL,'2',NULL,NULL,NULL,NULL,'SORBATO DE POTASIO',NULL,'40302002001017','N','VIG','13','55.180000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','47',NULL,NULL,'2',NULL,NULL,NULL,NULL,'T 61 L  TRANSGLUTAMINAZA',NULL,'40302002001017','N','VIG','13','435.000000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','48',NULL,NULL,'2',NULL,NULL,NULL,NULL,'CANELA NATURAL',NULL,'40302002001003','N','VIG','14','104.440000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','49',NULL,NULL,'2',NULL,NULL,NULL,NULL,'COLORANTE AMARILLO HUEVO',NULL,'40302002001003','N','VIG','15','0.060000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','50',NULL,NULL,'2',NULL,NULL,NULL,NULL,'COLORANTE AZUL',NULL,'40302002001003','N','VIG','15','0.200000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','51',NULL,NULL,'2',NULL,NULL,NULL,NULL,'COLORANTE ROJO AMARANTO FRUTILLA',NULL,'40302002001003','N','VIG','15','0.070000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','52',NULL,NULL,'2',NULL,NULL,NULL,NULL,'COLORANTE ROJO COCHINILLA',NULL,'40302002001003','N','VIG','15','0.550000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','53',NULL,NULL,'2',NULL,NULL,NULL,NULL,'COLORANTE UVA MORADA',NULL,'40302002001003','N','VIG','15','0.100000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','54',NULL,NULL,'2',NULL,NULL,NULL,NULL,'COLORANTE VERDE MANZANA',NULL,'40302002001003','N','VIG','15','103.530000','GR','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','55',NULL,NULL,'2',NULL,NULL,NULL,NULL,'CUAJO',NULL,'40302002001004','N','VIG','16','0.740000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','56',NULL,NULL,'2',NULL,NULL,NULL,NULL,'EDULDIET',NULL,'40302002001010','N','VIG','17','95.700000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','57',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BLS P/CHICOTRON 80 ML',NULL,'40302004002002','N','VIG','1','27.800000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','58',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BLS P/LECHE CON AVENA DESAYUNO ESCOLAR',NULL,'40302004002015','N','VIG','1','34.100000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','59',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BLS P/LECHE SABORIZADA DESAYUNO ESCOLAR',NULL,'40302004002005','N','VIG','1','36.910000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','60',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BLS. P/YOGURT SUBSIDIO 120 ML ',NULL,'40302004002001','N','VIG','1','29.320000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','61',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BLS. P/YOGURT 120 ML',NULL,'40302004002001','N','VIG','1','29.320000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','62',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BLS P/YOGURT 150 ML ESCOLAR',NULL,'40302004002001','N','VIG','1','36.680000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','63',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BOL. P/CHICOLIN 1LT',NULL,'40302004002002','N','VIG','1','28.270000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','64',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BOL. P/CHICOTRON 1 LT',NULL,'40302004002002','N','VIG','1','30.680000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','65',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BOL. P/CHICOTRON 150 CC',NULL,'40302004002002','N','VIG','1','33.150000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','66',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BOL. P/CREMA DE LECHE',NULL,'40302004002016','N','VIG','1','23.200000','PQ','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','67',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BOL. PIL CHUQUISACA 1  LT',NULL,'40302004002003','N','VIG','1','33.250000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','68',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BOL. P/ILFRUT  NARANJA',NULL,'40302004002007','N','VIG','1','27.880000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','69',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BOL. P/ILFRUT DURAZNO',NULL,'40302004002007','N','VIG','1','33.300000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','70',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BOL. P/ILFRUT MANZANA',NULL,'40302004002007','N','VIG','1','33.230000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','71',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BOL. P/LECHE C/AVENA 160 ML',NULL,'40302004002015','N','VIG','1','33.150000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','72',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BOL P/LECHE MALTEADA 150 ML',NULL,'40302004002005','N','VIG','1','39.830000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','73',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BOL. P/LECHE NATURAL 1 LT',NULL,'40302004002003','N','VIG','1','32.370000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','74',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BOL. P/LECHE NATURAL 950 ML SUBSIDIO',NULL,'40302004002003','N','VIG','1','32.360000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','75',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BOL. P/LECHE SAB. FRUTILLA  1 LT',NULL,'40302004002005','N','VIG','1','32.390000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','76',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BOL. P/LECHE SAB. FRUTILLA 160 CC',NULL,'40302004002005','N','VIG','1','32.360000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','77',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BOL P/LECHE SABORIZADA SUBSIDIO 1 LT',NULL,'40302004002005','N','VIG','1','40.170000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','78',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BOL. P/QUESO',NULL,'40302004002006','N','VIG','1','1.110000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','79',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BOL. P/YOGURT  ESCOLAR 80 CC',NULL,'40302004002001','N','VIG','1','29.320000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','80',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BOLSA TERMOCONTRAIBLES P/BOT. 2 LT',NULL,'40302004002018','N','VIG','1','26.100000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','81',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BOLSAS DE EMPAQUE',NULL,'40302004002018','N','VIG','1','21.280000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','82',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BOT. JUGO  DE FRUTAS 2  LT',NULL,'40302004002017','N','VIG','1','0.990000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','83',NULL,NULL,'3',NULL,NULL,NULL,NULL,'BOTELLAS DE 2 LT CRISTAL ESTRIADO',NULL,'40302004002009','N','VIG','1','0.910000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','84',NULL,NULL,'3',NULL,NULL,NULL,NULL,'EMPAQUETADURAS CLAMP DE 2\"',NULL,'40302004002018','N','VIG','1','18.270000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','85',NULL,NULL,'3',NULL,NULL,NULL,NULL,'EMPAQUETADURAS CLAMPS   1 1/2\"',NULL,'40302004002018','N','VIG','1','18.270000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','86',NULL,NULL,'3',NULL,NULL,NULL,NULL,'ETIQUETAS PARA YOGURT 2 LT CHIRIMOYA',NULL,'40302004002018','N','VIG','1','0.430000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','87',NULL,NULL,'3',NULL,NULL,NULL,NULL,'ETIQUETAS PARA YOGURT 2 LT-COCO',NULL,'40302004002018','N','VIG','1','0.350000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','88',NULL,NULL,'3',NULL,NULL,NULL,NULL,'ETIQUETAS PARA YOGURT 2 LT-DURAZNO',NULL,'40302004002018','N','VIG','1','0.350000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','89',NULL,NULL,'3',NULL,NULL,NULL,NULL,'ETIQUETAS PARA YOGURT 2 LT-FRUTILLA',NULL,'40302004002018','N','VIG','1','0.350000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','90',NULL,NULL,'3',NULL,NULL,NULL,NULL,'ETIQUETAS PARA YOGURT 2 LT-MORA',NULL,'40302004002018','N','VIG','1','0.350000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','91',NULL,NULL,'3',NULL,NULL,NULL,NULL,'ETIQUETAS P/BIOYOGURT 2 LT',NULL,'40302004002018','N','VIG','1','0.260000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','92',NULL,NULL,'3',NULL,NULL,NULL,NULL,'ETIQUETAS P/YOGURT FRUTADO 1 LT COMERCIAL',NULL,'40302004002018','N','VIG','1','0.340000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','93',NULL,NULL,'3',NULL,NULL,NULL,NULL,'ETIQUETAS QUESO EDAM - SUBSISDIO',NULL,'40302004002018','N','VIG','1','0.200000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','94',NULL,NULL,'3',NULL,NULL,NULL,NULL,'ETQ PARA YOGURT FRUTADO SUBSIDIO 1 LT',NULL,'40302004002018','N','VIG','1','0.220000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','95',NULL,NULL,'3',NULL,NULL,NULL,NULL,'TAPAS PARA BOTELLA DE 2 LT',NULL,'40302004002014','N','VIG','1','0.110000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','96',NULL,NULL,'3',NULL,NULL,NULL,NULL,'TAPAS Y BOTELLAS P/FRUTADO',NULL,'40302004002008','N','VIG','1','1.330000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','97',NULL,NULL,'3',NULL,NULL,NULL,NULL,'VASOS P/YOGURT FRUTADO 140 ML',NULL,'40302004002011','N','VIG','1','0.470000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','98',NULL,NULL,'3',NULL,NULL,NULL,NULL,'VASOS P/YOGURT FRUTADO 750 ML',NULL,'40302004002010','N','VIG','1','1.710000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','99',NULL,NULL,'3',NULL,NULL,NULL,NULL,'CINTA FECHADOR',NULL,'40302004002018','N','VIG','2','30.430000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','100',NULL,NULL,'3',NULL,NULL,NULL,NULL,'METIL ETIL CETONA 9154',NULL,'40302004002018','N','VIG','3','1.340000','ML','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','101',NULL,NULL,'3',NULL,NULL,NULL,NULL,'TINTA KF 9660',NULL,'40302004002018','N','VIG','3','1.620000','ML','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','102',NULL,NULL,'3',NULL,NULL,NULL,NULL,'TINTA 9570',NULL,'40302004002018','N','VIG','3','1.730000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','103',NULL,NULL,'3',NULL,NULL,NULL,NULL,'ADDITIVO 8661',NULL,'40302004002018','N','VIG','4','0.280000','ML','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','104',NULL,NULL,'3',NULL,NULL,NULL,NULL,'METIL ETIL CETONA 5191',NULL,'40302004002018','N','VIG','4','0.170000','ML','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','105',NULL,NULL,'3',NULL,NULL,NULL,NULL,'ALCOHOL',NULL,'40302004004001','N','VIG','5','9.940000','LT','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','106',NULL,NULL,'3',NULL,NULL,NULL,NULL,'PICETA GRADUADA DE 1000 ML',NULL,'40302004004002','N','VIG','5','39.150000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','107',NULL,NULL,'3',NULL,NULL,NULL,NULL,'PICETA GRADUADA DE 500 ML',NULL,'40302004004002','N','VIG','5','23.490000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','108',NULL,NULL,'3',NULL,NULL,NULL,NULL,'ACIDO SULFURICO',NULL,'40302004004002','N','VIG','5','0.170000','ML','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','109',NULL,NULL,'3',NULL,NULL,NULL,NULL,'ACIDO NITRICO',NULL,'40302004001003','N','VIG','6','7.080000','LT','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','110',NULL,NULL,'3',NULL,NULL,NULL,NULL,'ADDITIVO 5661',NULL,'40302004001003','N','VIG','6','225.330000','LT','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','111',NULL,NULL,'3',NULL,NULL,NULL,NULL,'ADITIVO  5551',NULL,'40302004001003','N','VIG','6','207.930000','LT','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','112',NULL,NULL,'3',NULL,NULL,NULL,NULL,'CLORO',NULL,'40302004001003','N','VIG','6','26.970000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','113',NULL,NULL,'3',NULL,NULL,NULL,NULL,'DETERGENTE',NULL,'40302004001003','N','VIG','6','2.380000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','114',NULL,NULL,'3',NULL,NULL,NULL,NULL,'SANIT-T-10',NULL,'40302004001003','N','VIG','6','56.550000','LT','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','115',NULL,NULL,'3',NULL,NULL,NULL,NULL,'SODA CAUSTICA',NULL,'40302004001003','N','VIG','6','9.080000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','116',NULL,NULL,'3',NULL,NULL,NULL,NULL,'PEROXIDO',NULL,'40302004001003','N','VIG','6','9.180000','KG','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','117',NULL,NULL,'3',NULL,NULL,NULL,NULL,'TEFLON DE MAQUINA',NULL,'40302004003001','N','VIG','7','276.280000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','118',NULL,NULL,'4',NULL,NULL,NULL,NULL,'LECHE NATURAL UHT 950 ML',NULL,'40301001001001','N','VIG','1','3.610000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','119',NULL,NULL,'4',NULL,NULL,NULL,NULL,'CHICOTRON 1LT',NULL,'40301001001001','N','VIG','2','3.490000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','120',NULL,NULL,'4',NULL,NULL,NULL,NULL,'CHICOTRON 100 CC',NULL,'40301001001001','N','VIG','2','0.380000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','121',NULL,NULL,'4',NULL,NULL,NULL,NULL,'CHICOTRON 150 CC',NULL,'40301001001001','N','VIG','2','0.610000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','122',NULL,NULL,'4',NULL,NULL,NULL,NULL,'CHICOTRON 160 CC',NULL,'40301001001001','N','VIG','2','0.710000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','123',NULL,NULL,'4',NULL,NULL,NULL,NULL,'LECHE C. AVENA SAB CANELA 160',NULL,'40301001001001','N','VIG','2','0.620000','UN','2');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','124',NULL,NULL,'4',NULL,NULL,NULL,NULL,'LECHE MALTEADA 150 ML',NULL,'40301001001001','N','VIG','2','0.680000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','125',NULL,NULL,'4',NULL,NULL,NULL,NULL,'LECHE SABORIZADA FRUTIKID 150',NULL,'40301001001001','N','VIG','2','0.580000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','126',NULL,NULL,'4',NULL,NULL,NULL,NULL,'LECHE SABORIZADA FRUTILLA 1LT',NULL,'40301001001001','N','VIG','2','3.340000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','127',NULL,NULL,'4',NULL,NULL,NULL,NULL,'LECHE SABORIZADA FRUTILLA 170',NULL,'40301001001001','N','VIG','2','0.800000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','128',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOGURT CHIRIMOYA 2LT',NULL,'40301001001001','N','VIG','1','9.910000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','129',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOGURT COCO 2LT',NULL,'40301001001001','N','VIG','1','12.500000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','130',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOGURT DURAZNO 2LT',NULL,'40301001001001','N','VIG','1','12.390000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','131',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOGURT FRUTILLA 2LT',NULL,'40301001001001','N','VIG','1','12.290000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','132',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOGURT MORA 2LT',NULL,'40301001001001','N','VIG','1','9.710000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','133',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOGURT NATURAL 2LT',NULL,'40301001001001','N','VIG','1','12.850000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','134',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOG. FRUTADO FRUTILLA BOT 1 LT',NULL,'40301001001001','N','VIG','2','7.360000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','135',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOG. FRUTADO FRUTILLA VASO 750',NULL,'40301001001001','N','VIG','2','5.480000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','136',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOGURT SACHET COCO 80 CC',NULL,'40301001001001','N','VIG','3','0.160000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','137',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOGURT SACHET DURAZNO 500 CC',NULL,'40301001001001','N','VIG','3','1.820000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','138',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOGURT SACHET DURAZNO 80 CC',NULL,'40301001001001','N','VIG','3','0.370000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','139',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOGURT SACHET FRUTILLA 120 CC',NULL,'40301001001001','N','VIG','3','0.600000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','140',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOGURT SACHET FRUTILLA 140 CC',NULL,'40301001001001','N','VIG','3','0.650000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','141',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOGURT SACHET FRUTILLA 150 CC',NULL,'40301001001001','N','VIG','3','0.550000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','142',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOGURT SACHET FRUTILLA 500 CC',NULL,'40301001001001','N','VIG','3','1.560000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','143',NULL,NULL,'5',NULL,NULL,NULL,NULL,'YOGURT SACHET FRUTILLA 80 CC',NULL,'40301001001001','N','VIG','3','0.380000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','144',NULL,NULL,'5',NULL,NULL,NULL,NULL,'ILFRUT DURAZNO 140CC',NULL,'40301001001001','N','VIG','4','0.300000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','145',NULL,NULL,'5',NULL,NULL,NULL,NULL,'ILFRUT JUGO NARANJA 160CC',NULL,'40301001001001','N','VIG','4','0.220000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','146',NULL,NULL,'5',NULL,NULL,NULL,NULL,'ILFRUT MANZANA 140CC',NULL,'40301001001001','N','VIG','4','0.300000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','147',NULL,NULL,'5',NULL,NULL,NULL,NULL,'JUGO DE FRUTAS 2 LT',NULL,'40301001001001','N','VIG','4','7.600000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','148',NULL,NULL,'6',NULL,NULL,NULL,NULL,'QUESO EDAM 500',NULL,'40301001001001','N','VIG','1','19.870000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','149',NULL,NULL,'6',NULL,NULL,NULL,NULL,'QUESO FRESCO 200 GR',NULL,'40301001001001','N','VIG','1','9.830000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','150',NULL,NULL,'6',NULL,NULL,NULL,NULL,'QUESO FRESCO 500 GR',NULL,'40301001001001','N','VIG','1','14.770000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','151',NULL,NULL,'6',NULL,NULL,NULL,NULL,'QUESO PRENSADO 500',NULL,'40301001001001','N','VIG','1','19.920000','UN','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','152',NULL,NULL,'2',NULL,NULL,NULL,NULL,'AGUA','H2O','40302002001017','N','VIG','18','1.000000','LT','1');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','1',NULL,NULL,'2',NULL,NULL,NULL,NULL,'LECHE CRUDA',NULL,'40302001001001','N','VIG','20','3.500000','LT','1');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','181',NULL,NULL,'1',NULL,NULL,NULL,NULL,'YOGURT-BASE',NULL,'40302001001001','N','VIG','1','1.000000','LT','0');
insert into `inv_articulos` (`no_cia`, `cod_art`, `control_valorado`, `cantiad_equi`, `cod_gru`, `cod_med_may`, `saldo_mon`, `stockmaximo`, `stockminimo`, `descri`, `nombrecorto`, `cuenta_art`, `vendible`, `estado`, `cod_sub`, `costo_uni`, `cod_med`, `version`) values('01','162',NULL,NULL,'2',NULL,NULL,NULL,NULL,'ACIDO ASCORBICO',NULL,'40302002001008','N','VIG','1','1.000000','KG','0');
