use eos;
CREATE TABLE articulos_paquete
(
    IDARTICULOSPAQUETE BIGINT PRIMARY KEY NOT NULL,
    CANTIDAD BIGINT,
    COD_ALM VARCHAR(255),
    COD_ART VARCHAR(255),
    ID_CUENTA BIGINT,
    IDCLIENTE BIGINT,
    IDPAQUETES BIGINT,
    NO_CIA VARCHAR(255),
    PRECIO DOUBLE,
    TOTAL DOUBLE
);
CREATE TABLE articulos_pedido
(
    IDARTICULOSPEDIDO BIGINT PRIMARY KEY NOT NULL,
    CAJA BIGINT,
    CANTIDAD BIGINT,
    COD_ALM VARCHAR(255),
    COD_ART VARCHAR(255),
    ID VARCHAR(255),
    ID1 BIGINT,
    ID_CUENTA BIGINT,
    NO_CIA VARCHAR(255),
    PEDIDO BIGINT,
    PRECIO DOUBLE,
    PRECIO_INV DOUBLE,
    PROMOCION BIGINT,
    REPOSICION BIGINT,
    TOTAL DOUBLE,
    TOTAL_INV BIGINT
);
CREATE TABLE cliente
(
    ID_PI BIGINT PRIMARY KEY NOT NULL,
    CODIGO VARCHAR(255),
    DIRECCION VARCHAR(255),
    NIT VARCHAR(255),
    TELEFONO INT,
    idtipocliente BIGINT,
    descuento DOUBLE,
    idretencion BIGINT,
    RAZONSOCIAL VARCHAR(100),
    TIPOCLIENTE VARCHAR(20)
);
CREATE TABLE compania
(
    IDCOMPANIA BIGINT PRIMARY KEY NOT NULL,
    CODIGO VARCHAR(255)
);
CREATE TABLE departamento
(
    IDDEPARTAMENTO BIGINT PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(20)
);
CREATE TABLE derechoacceso
(
    PERMISO INT,
    IDROL BIGINT NOT NULL,
    IDFUNCIONALIDAD BIGINT NOT NULL,
    IDCOMPANIA BIGINT,
    IDMODULO BIGINT,
    PRIMARY KEY (IDROL, IDFUNCIONALIDAD)
);
CREATE TABLE distribuidor
(
    PI_ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    OBSERVACION VARCHAR(255)
);
CREATE TABLE empleado
(
    IDEMPLEADO BIGINT PRIMARY KEY NOT NULL,
    CODIGOEMPLEADO VARCHAR(255),
    CODIGOMARCACION VARCHAR(255),
    FECHAINGRESO DATE,
    FECHASALIDA DATE,
    FLAGAFP BIGINT,
    FLAGCONTROL BIGINT,
    FLAGJUBILADO BIGINT,
    FLAGRET BIGINT,
    IDCOMPANIA BIGINT,
    IDUNIDADNEGOCIO BIGINT,
    SALARIO DOUBLE,
    TIPODEPAGO VARCHAR(255)
);
CREATE TABLE estado_pedidos
(
    IDESTADOPEDIDO BIGINT PRIMARY KEY NOT NULL,
    ESTADO VARCHAR(255)
);
CREATE TABLE funcionalidad
(
    IDFUNCIONALIDAD BIGINT PRIMARY KEY NOT NULL,
    CODIGO VARCHAR(255),
    DESCRIPCION LONGTEXT,
    IDCOMPANIA BIGINT,
    NOMBRERECURSO VARCHAR(255),
    PERMISO INT,
    IDMODULO BIGINT
);
CREATE TABLE id_gen
(
    GEN_NAME VARCHAR(30) PRIMARY KEY NOT NULL,
    GEN_VAL BIGINT
);
CREATE TABLE institucion
(
    PI_ID BIGINT PRIMARY KEY NOT NULL,
    RAZONSOCIAL VARCHAR(255)
);
CREATE TABLE inv_articulos
(
    CANTIAD_EQUI DOUBLE,
    COD_MED VARCHAR(255),
    COD_MED_MAY VARCHAR(255),
    COD_SUB VARCHAR(255),
    CONTROL_VALORADO VARCHAR(255),
    COSTO_UNI DOUBLE,
    CUENTA_ART VARCHAR(255),
    DESCRI VARCHAR(255),
    ESTADO VARCHAR(255),
    NOMBRECORTO VARCHAR(255),
    SALDO_MON DOUBLE,
    STOCKMAXIMO DOUBLE,
    STOCKMINIMO DOUBLE,
    VENDIBLE VARCHAR(255),
    VERSION BIGINT,
    COD_ART VARCHAR(255) NOT NULL,
    NO_CIA VARCHAR(255) NOT NULL,
    COD_GRU VARCHAR(255),
    PRIMARY KEY (COD_ART, NO_CIA)
);
CREATE TABLE inv_grupos
(
    CUENTA_INV VARCHAR(255),
    DESCRI VARCHAR(255),
    TIPO VARCHAR(255),
    VERSION BIGINT,
    COD_GRU VARCHAR(255) NOT NULL,
    NO_CIA VARCHAR(255) NOT NULL,
    PRIMARY KEY (COD_GRU, NO_CIA)
);
CREATE TABLE modulo
(
    IDMODULO BIGINT PRIMARY KEY NOT NULL,
    DESCRIPCION LONGTEXT,
    IDCOMPANIA BIGINT,
    NOMBRERECURSO VARCHAR(255)
);
CREATE TABLE modulocompania
(
    ACTIVO INT,
    IDCOMPANIA BIGINT NOT NULL,
    IDMODULO BIGINT NOT NULL,
    PRIMARY KEY (IDCOMPANIA, IDMODULO)
);
CREATE TABLE paquetes
(
    IDPAQUETES BIGINT PRIMARY KEY NOT NULL,
    ACTIVO VARCHAR(255),
    CUENTA_ID BIGINT,
    FECHA_FIN DATE,
    FECHA_INICIO DATE,
    NOMBRE VARCHAR(255),
    TOTAL DOUBLE
);
CREATE TABLE pedidos
(
    IDPEDIDOS BIGINT PRIMARY KEY NOT NULL,
    DESCRIPCION VARCHAR(255),
    FACTURA VARCHAR(255),
    FECHA_A_PAGAR DATE,
    FECHA_ENTREGA DATE,
    FECHA_PEDIDO DATE,
    ID VARCHAR(255),
    ID1 BIGINT,
    IDDIRECCION BIGINT,
    IDZONA BIGINT,
    OBSERVACION VARCHAR(255),
    PORCEN_DESCUENTO DOUBLE,
    PORCEN_RETENCION DOUBLE,
    SUPERVISOR BIGINT,
    TIPO_PEDIDO VARCHAR(255),
    TOTAL DOUBLE,
    ESTADO_PEDIDO BIGINT,
    IDCLIENTE BIGINT,
    IDDISTRIBUIDOR BIGINT,
    IDEMPLEADO BIGINT,
    IDTIPOPEDIDO BIGINT,
    ESTADO VARCHAR(15)
);
CREATE TABLE persona
(
    IDPERSONA BIGINT PRIMARY KEY NOT NULL,
    AM VARCHAR(255),
    AP VARCHAR(255),
    CEM_COD VARCHAR(255),
    EST_CIVIL VARCHAR(255),
    FECHA_NAC DATE,
    NOM VARCHAR(255),
    NRO_DOC VARCHAR(255),
    OCU_COD VARCHAR(255),
    SEXO VARCHAR(255),
    SIS_COD VARCHAR(255),
    TDO_COD VARCHAR(255),
    TIPO_PERSONA VARCHAR(45),
    DIRECCION VARCHAR(100),
    TELEFONO VARCHAR(15),
    NIT VARCHAR(20),
    CODIGOCLIENTE VARCHAR(10),
    RAZONSOCIAL VARCHAR(45),
    OBSERVACION VARCHAR(100),
    IDRETENCION BIGINT,
    IDTIPOCLIENTE BIGINT,
    IDDEPARTAMENTO BIGINT,
    descuento DOUBLE
);
CREATE TABLE retencion
(
    IDRETENCION BIGINT PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(255),
    PORCENTAGE DOUBLE,
    ESTADO BIT
);
CREATE TABLE rol
(
    IDROL BIGINT PRIMARY KEY NOT NULL,
    DESCRIPCION LONGTEXT,
    IDCOMPANIA BIGINT,
    NOMBRE VARCHAR(255),
    VERSION BIGINT
);
CREATE TABLE tipocliente
(
    IDTIPOCLIENTE BIGINT PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(255)
);
CREATE TABLE tipopedido
(
    IDTIPOPEDIDO BIGINT PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(255)
);
CREATE TABLE usuario
(
    IDUSUARIO BIGINT PRIMARY KEY NOT NULL,
    CLAVE VARCHAR(255),
    EMAIL VARCHAR(255),
    FECHACREACION DATETIME,
    NUMEROUSUARIO VARCHAR(255),
    USUARIO VARCHAR(255),
    USUARIOFINANZAS INT,
    VERSION BIGINT,
    IDCOMPANIA BIGINT
);
CREATE TABLE usuariorol
(
    IDROL BIGINT NOT NULL,
    IDUSUARIO BIGINT NOT NULL,
    PRIMARY KEY (IDROL, IDUSUARIO)
);
CREATE TABLE ventaarticulo
(
    IDVENTAARTICULO BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    PRECIO DOUBLE,
    NO_CIA VARCHAR(255),
    COD_ART VARCHAR(255)
);
CREATE TABLE ventacliente
(
    IDVENTACLIENTE BIGINT PRIMARY KEY NOT NULL,
    PRECIOESPECIAL DOUBLE,
    IDVENTAARTICULO BIGINT NOT NULL,
    IDPERSONA BIGINT NOT NULL
);
ALTER TABLE articulos_pedido ADD FOREIGN KEY (COD_ART, NO_CIA) REFERENCES inv_articulos (COD_ART, NO_CIA);
CREATE INDEX ARTICULOS_PEDIDO_INV_ARTICULOS_FK_idx ON articulos_pedido (COD_ART, NO_CIA);
ALTER TABLE cliente ADD FOREIGN KEY (idretencion) REFERENCES retencion (IDRETENCION);
ALTER TABLE cliente ADD FOREIGN KEY (ID_PI) REFERENCES persona (IDPERSONA) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE cliente ADD FOREIGN KEY (idtipocliente) REFERENCES tipocliente (IDTIPOCLIENTE);
CREATE INDEX fk_cliente_tipocliente_idx ON cliente (idtipocliente);
CREATE INDEX FK_liente_retencion_idx ON cliente (idretencion);
ALTER TABLE derechoacceso ADD FOREIGN KEY (IDCOMPANIA, IDMODULO) REFERENCES modulocompania (IDCOMPANIA, IDMODULO);
ALTER TABLE derechoacceso ADD FOREIGN KEY (IDFUNCIONALIDAD) REFERENCES funcionalidad (IDFUNCIONALIDAD);
ALTER TABLE derechoacceso ADD FOREIGN KEY (IDROL) REFERENCES rol (IDROL);
CREATE INDEX FK_derechoacceso_IDCOMPANIA ON derechoacceso (IDCOMPANIA, IDMODULO);
CREATE INDEX FK_derechoacceso_IDFUNCIONALIDAD ON derechoacceso (IDFUNCIONALIDAD);
ALTER TABLE funcionalidad ADD FOREIGN KEY (IDMODULO) REFERENCES modulo (IDMODULO);
CREATE INDEX FK_funcionalidad_IDMODULO ON funcionalidad (IDMODULO);
CREATE UNIQUE INDEX GEN_NAME_UNIQUE ON id_gen (GEN_NAME);
ALTER TABLE inv_articulos ADD FOREIGN KEY (COD_GRU, NO_CIA) REFERENCES inv_grupos (COD_GRU, NO_CIA);
CREATE INDEX FK_inv_articulos_COD_GRU ON inv_articulos (COD_GRU, NO_CIA);
ALTER TABLE modulocompania ADD FOREIGN KEY (IDMODULO) REFERENCES modulo (IDMODULO);
CREATE INDEX FK_modulocompania_IDMODULO ON modulocompania (IDMODULO);
ALTER TABLE pedidos ADD FOREIGN KEY (ESTADO_PEDIDO) REFERENCES estado_pedidos (IDESTADOPEDIDO);
ALTER TABLE pedidos ADD FOREIGN KEY (IDDISTRIBUIDOR) REFERENCES distribuidor (PI_ID);
ALTER TABLE pedidos ADD FOREIGN KEY (IDEMPLEADO) REFERENCES empleado (IDEMPLEADO);
ALTER TABLE pedidos ADD FOREIGN KEY (IDTIPOPEDIDO) REFERENCES tipopedido (IDTIPOPEDIDO);
CREATE INDEX FK_pedidos_ESTADO_PEDIDO ON pedidos (ESTADO_PEDIDO);
CREATE INDEX FK_pedidos_IDDISTRIBUIDOR ON pedidos (IDDISTRIBUIDOR);
CREATE INDEX FK_pedidos_IDEMPLEADO ON pedidos (IDEMPLEADO);
CREATE INDEX FK_pedidos_IDTIPOPEDIDO ON pedidos (IDTIPOPEDIDO);
ALTER TABLE persona ADD FOREIGN KEY (IDDEPARTAMENTO) REFERENCES departamento (IDDEPARTAMENTO);
ALTER TABLE persona ADD FOREIGN KEY (IDRETENCION) REFERENCES retencion (IDRETENCION);
ALTER TABLE persona ADD FOREIGN KEY (IDTIPOCLIENTE) REFERENCES tipocliente (IDTIPOCLIENTE);
CREATE UNIQUE INDEX IDPERSONA_UNIQUE ON persona (IDPERSONA);
CREATE INDEX FK_PERSONAS_DEPARTAMENTO_idx ON persona (IDDEPARTAMENTO);
CREATE INDEX FK_PERSONAS_RETENCION_idx ON persona (IDRETENCION);
CREATE INDEX FK_PERSONAS_TIPOCLIENTE_idx ON persona (IDTIPOCLIENTE);
ALTER TABLE usuario ADD FOREIGN KEY (IDCOMPANIA) REFERENCES compania (IDCOMPANIA);
CREATE INDEX FK_usuario_IDCOMPANIA ON usuario (IDCOMPANIA);
ALTER TABLE usuariorol ADD FOREIGN KEY (IDROL) REFERENCES rol (IDROL);
ALTER TABLE usuariorol ADD FOREIGN KEY (IDUSUARIO) REFERENCES usuario (IDUSUARIO);
CREATE INDEX FK_usuariorol_IDUSUARIO ON usuariorol (IDUSUARIO);
ALTER TABLE ventaarticulo ADD FOREIGN KEY (COD_ART, NO_CIA) REFERENCES inv_articulos (COD_ART, NO_CIA);
CREATE INDEX FK_ventaarticulo_COD_ART ON ventaarticulo (COD_ART, NO_CIA);
ALTER TABLE ventacliente ADD FOREIGN KEY (IDPERSONA) REFERENCES persona (IDPERSONA);
ALTER TABLE ventacliente ADD FOREIGN KEY (IDVENTAARTICULO) REFERENCES ventaarticulo (IDVENTAARTICULO);
CREATE INDEX VentaCliente_CLIENTE_FK ON ventacliente (IDPERSONA);
CREATE INDEX VentaCliente_VENTAARTICULO_FK ON ventacliente (IDVENTAARTICULO);
