use eos;
--------------------------------------------------------
--  DDL for Table COMPANIA
--------------------------------------------------------

  CREATE TABLE EOS.COMPANIA 
   (	IDCOMPANIA BIGINT(24), 
		CODIGO VARCHAR(255)
   );
--------------------------------------------------------
--  DDL for Index COMPANIA_PK
--------------------------------------------------------
ALTER TABLE EOS.COMPANIA ADD CONSTRAINT COMPANIA_PK PRIMARY KEY ( IDCOMPANIA) ;

  

CREATE TABLE EOS.DERECHOACCESO
  (
    IDFUNCIONALIDAD BIGINT(24)  NOT NULL ,
    IDROL           BIGINT(24)  NOT NULL ,
    PERMISO         int (3) ,
    IDCOMPANIA      BIGINT(24)  ,
    IDMODULO        BIGINT(24) 
  ) ;
  ALTER TABLE EOS.DERECHOACCESO ADD CONSTRAINT DERECHOACCESO_PK PRIMARY KEY ( IDFUNCIONALIDAD, IDROL ) ;
  
  CREATE TABLE EOS.FUNCIONALIDAD
    (
      IDFUNCIONALIDAD BIGINT(24)  NOT NULL ,
      CODIGO          VARCHAR (40 ) ,
      DESCRIPCION text ,
      IDMODULO      BIGINT(24)  ,
      PERMISO       INT (3) ,
      NOMBRERECURSO VARCHAR (100 ) ,
      IDCOMPANIA    BIGINT(24) 
    ) ;
  ALTER TABLE EOS.FUNCIONALIDAD ADD CONSTRAINT FUNCIONALIDAD_PK PRIMARY KEY ( IDFUNCIONALIDAD ) ;
  CREATE TABLE EOS.MODULO
    (
      IDMODULO BIGINT(24)  NOT NULL ,
      DESCRIPCION text ,
      NOMBRERECURSO VARCHAR (150 ) ,
      IDCOMPANIA    BIGINT(24) 
    ) ;
  ALTER TABLE EOS.MODULO ADD CONSTRAINT MODULO_PK PRIMARY KEY ( IDMODULO ) ;
  CREATE TABLE EOS.MODULOCOMPANIA
    (
      IDCOMPANIA BIGINT(24)  NOT NULL ,
      IDMODULO   BIGINT(24)  NOT NULL ,
      ACTIVO     INT (10)
    ) ;
  ALTER TABLE EOS.MODULOCOMPANIA ADD CONSTRAINT MODULOCOMPANIA_PK PRIMARY KEY ( IDCOMPANIA, IDMODULO ) ;
  CREATE TABLE EOS.ROL
    (
      IDROL BIGINT(24)  NOT NULL ,
      DESCRIPCION text ,
      NOMBRE     VARCHAR (150 ) ,
      VERSION    BIGINT(24)  ,
      IDCOMPANIA BIGINT(24) 
    ) ;
  ALTER TABLE EOS.ROL ADD CONSTRAINT ROL_PK PRIMARY KEY ( IDROL ) ;
  CREATE TABLE EOS.USUARIO
    (
      IDUSUARIO       BIGINT(24)  NOT NULL ,
      FECHACREACION   TIMESTAMP ,
      EMAIL           VARCHAR (100 ) ,
      NUMEROUSUARIO   VARCHAR (4 ) ,
      USUARIOFINANZAS INT (10) ,
      CLAVE           VARCHAR (200 ) ,
      USUARIO         VARCHAR (50 ) ,
      VERSION         BIGINT(24)  ,
      IDCOMPANIA      BIGINT(24) 
    ) ;
  ALTER TABLE EOS.USUARIO ADD CONSTRAINT USUARIO_PK PRIMARY KEY ( IDUSUARIO ) ;
  CREATE TABLE EOS.USUARIOROL
    (
      IDROL     BIGINT(24)  NOT NULL ,
      IDUSUARIO BIGINT(24) 
    ) ;
  ALTER TABLE EOS.DERECHOACCESO ADD CONSTRAINT DERECHOACCESO_FUNCIONALID_FK1 FOREIGN KEY ( IDFUNCIONALIDAD ) REFERENCES EOS.FUNCIONALIDAD ( IDFUNCIONALIDAD ) ;
  ALTER TABLE EOS.DERECHOACCESO ADD CONSTRAINT DERECHOACCESO_MODULOCOMPA_FK1 FOREIGN KEY ( IDCOMPANIA, IDMODULO ) REFERENCES EOS.MODULOCOMPANIA ( IDCOMPANIA, IDMODULO ) ;
  ALTER TABLE EOS.DERECHOACCESO ADD CONSTRAINT DERECHOACCESO_ROL_FK1 FOREIGN KEY ( IDROL ) REFERENCES EOS.ROL ( IDROL ) ;
  ALTER TABLE EOS.FUNCIONALIDAD ADD CONSTRAINT FUNCIONALIDAD_MODULO_FK1 FOREIGN KEY ( IDMODULO ) REFERENCES EOS.MODULO ( IDMODULO ) ;
  ALTER TABLE EOS.MODULOCOMPANIA ADD CONSTRAINT MODULOCOMPANIA_MODULO_FK1 FOREIGN KEY ( IDMODULO ) REFERENCES EOS.MODULO ( IDMODULO ) ;
  ALTER TABLE EOS.USUARIOROL ADD CONSTRAINT USUARIOROL_ROL_FK1 FOREIGN KEY ( IDROL ) REFERENCES EOS.ROL ( IDROL ) ;
  ALTER TABLE EOS.USUARIOROL ADD CONSTRAINT USUARIOROL_USUARIO_FK1 FOREIGN KEY ( IDUSUARIO ) REFERENCES EOS.USUARIO ( IDUSUARIO ) ;  
  ALTER TABLE EOS.USUARIO ADD CONSTRAINT USUARIO_COMPANIA_FK1 FOREIGN KEY ( IDCOMPANIA ) REFERENCES EOS.COMPANIA ( IDCOMPANIA ) ;

Insert into COMPANIA (IDCOMPANIA,CODIGO) values ('1','ILVA');

Insert into USUARIO (IDUSUARIO,FECHACREACION,EMAIL,NUMEROUSUARIO,USUARIOFINANZAS,CLAVE,USUARIO,VERSION,IDCOMPANIA) values ('1',timestamp('12/01/14'),null,null,null,'b452ec70e4f65b0355a194217ec9ba6000e045f7458d3abbab1a7c72ef1aef00c8292898e8bcd2161f59f783d995211e2c0cb5a72fc15148f8833a5eec4f2008','ilva','0','1');
