CREATE TABLE articulos_paquete
(
    IDARTICULOSPAQUETE BIGINT PRIMARY KEY NOT NULL,
    CANTIDAD BIGINT,
    COD_ALM VARCHAR(255),
    COD_ART VARCHAR(255),
    ID_CUENTA BIGINT,
    IDCLIENTE BIGINT,
    IDPAQUETES BIGINT,
    NO_CIA VARCHAR(255),
    PRECIO DOUBLE,
    TOTAL DOUBLE
);
CREATE TABLE articulos_pedido
(
    IDARTICULOSPEDIDO BIGINT PRIMARY KEY NOT NULL,
    CAJA BIGINT,
    CANTIDAD INT,
    COD_ALM VARCHAR(255),
    COD_ART VARCHAR(255),
    NO_CIA VARCHAR(255),
    PRECIO DOUBLE,
    PRECIO_INV DOUBLE,
    PROMOCION INT,
    REPOSICION INT,
    TOTAL INT,
    TOTAL_INV INT,
    IMPORTE DOUBLE NOT NULL,
    IDPEDIDOS BIGINT,
    estado VARCHAR(20)
);
CREATE TABLE compania
(
    IDCOMPANIA BIGINT PRIMARY KEY NOT NULL,
    CODIGO VARCHAR(255)
);
CREATE TABLE departamento
(
    IDDEPARTAMENTO BIGINT PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(20)
);
CREATE TABLE derechoacceso
(
    PERMISO INT,
    IDROL BIGINT NOT NULL,
    IDFUNCIONALIDAD BIGINT NOT NULL,
    IDCOMPANIA BIGINT,
    IDMODULO BIGINT,
    PRIMARY KEY (IDROL, IDFUNCIONALIDAD)
);
CREATE TABLE distribuidor
(
    PI_ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    OBSERVACION VARCHAR(255)
);
CREATE TABLE dosificacion
(
    IDDOSIFICACION BIGINT PRIMARY KEY NOT NULL,
    NROAUTORIZACION BIGINT,
    FECHAVENCIMIENTO DATE,
    LLAVE VARCHAR(100),
    ESTADO VARCHAR(15),
    FACTURADEL BIGINT,
    FACTURAAL BIGINT,
    NUMEROACTUAL BIGINT
);
CREATE TABLE empleado
(
    IDEMPLEADO BIGINT PRIMARY KEY NOT NULL,
    CODIGOEMPLEADO VARCHAR(255),
    CODIGOMARCACION VARCHAR(255),
    FECHAINGRESO DATE,
    FECHASALIDA DATE,
    FLAGAFP BIGINT,
    FLAGCONTROL BIGINT,
    FLAGJUBILADO BIGINT,
    FLAGRET BIGINT,
    IDCOMPANIA BIGINT,
    IDUNIDADNEGOCIO BIGINT,
    SALARIO DOUBLE,
    TIPODEPAGO VARCHAR(255)
);
CREATE TABLE estado_pedidos
(
    IDESTADOPEDIDO BIGINT PRIMARY KEY NOT NULL,
    ESTADO VARCHAR(255)
);
CREATE TABLE funcionalidad
(
    IDFUNCIONALIDAD BIGINT PRIMARY KEY NOT NULL,
    CODIGO VARCHAR(255),
    DESCRIPCION LONGTEXT,
    IDCOMPANIA BIGINT,
    NOMBRERECURSO VARCHAR(255),
    PERMISO INT,
    IDMODULO BIGINT
);
CREATE TABLE id_gen
(
    GEN_NAME VARCHAR(30) PRIMARY KEY NOT NULL,
    GEN_VAL BIGINT
);
CREATE TABLE impresionfactura
(
    IDIMPRECIONFACTURA BIGINT PRIMARY KEY NOT NULL,
    FECHAIMPRESION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TIPO VARCHAR(10),
    IDMOVIMIENTO BIGINT NOT NULL,
    IDUSUARIO BIGINT NOT NULL,
    IDDOSIFICACION BIGINT
);
CREATE TABLE institucion
(
    PI_ID BIGINT PRIMARY KEY NOT NULL,
    RAZONSOCIAL VARCHAR(255)
);
CREATE TABLE inv_articulos
(
    CANTIAD_EQUI DOUBLE,
    COD_MED VARCHAR(255),
    COD_MED_MAY VARCHAR(255),
    COD_SUB VARCHAR(255),
    CONTROL_VALORADO VARCHAR(255),
    COSTO_UNI DOUBLE,
    CUENTA_ART VARCHAR(255),
    DESCRI VARCHAR(255),
    ESTADO VARCHAR(255),
    NOMBRECORTO VARCHAR(255),
    SALDO_MON DOUBLE,
    STOCKMAXIMO DOUBLE,
    STOCKMINIMO DOUBLE,
    VENDIBLE VARCHAR(255),
    VERSION BIGINT,
    COD_ART VARCHAR(255) NOT NULL,
    NO_CIA VARCHAR(255) NOT NULL,
    COD_GRU VARCHAR(255),
    PRIMARY KEY (COD_ART, NO_CIA)
);
CREATE TABLE inv_grupos
(
    CUENTA_INV VARCHAR(255),
    DESCRI VARCHAR(255),
    TIPO VARCHAR(255),
    VERSION BIGINT,
    COD_GRU VARCHAR(255) NOT NULL,
    NO_CIA VARCHAR(255) NOT NULL,
    PRIMARY KEY (COD_GRU, NO_CIA)
);
CREATE TABLE modulo
(
    IDMODULO BIGINT PRIMARY KEY NOT NULL,
    DESCRIPCION LONGTEXT,
    IDCOMPANIA BIGINT,
    NOMBRERECURSO VARCHAR(255)
);
CREATE TABLE modulocompania
(
    ACTIVO INT,
    IDCOMPANIA BIGINT NOT NULL,
    IDMODULO BIGINT NOT NULL,
    PRIMARY KEY (IDCOMPANIA, IDMODULO)
);
CREATE TABLE movimiento
(
    IDMOVIMIENTO BIGINT PRIMARY KEY NOT NULL,
    GLOSA VARCHAR(300),
    ESTADO VARCHAR(15),
    CODESTRUCT VARCHAR(30),
    MONEDA VARCHAR(10),
    NROFACTURA VARCHAR(30),
    CODIGOCONTROL VARCHAR(30),
    TIPOPAGO VARCHAR(10),
    TIPOCAMBIO DOUBLE,
    FECHAREGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    IDPEDIDOS BIGINT NOT NULL
);
CREATE TABLE paquetes
(
    IDPAQUETES BIGINT PRIMARY KEY NOT NULL,
    ACTIVO VARCHAR(255),
    CUENTA_ID BIGINT,
    FECHA_FIN DATE,
    FECHA_INICIO DATE,
    NOMBRE VARCHAR(255),
    TOTAL DOUBLE
);
CREATE TABLE pedidos
(
    IDPEDIDOS BIGINT PRIMARY KEY NOT NULL,
    DESCRIPCION VARCHAR(255),
    FACTURA VARCHAR(255),
    FECHA_A_PAGAR DATE,
    FECHA_ENTREGA DATE,
    FECHA_PEDIDO DATE,
    IDDIRECCION BIGINT,
    IDZONA BIGINT,
    OBSERVACION VARCHAR(255),
    PORCEN_DESCUENTO DOUBLE,
    PORCEN_RETENCION DOUBLE,
    SUPERVISOR BIGINT,
    TOTAL DOUBLE,
    ESTADO_PEDIDO BIGINT,
    IDCLIENTE BIGINT,
    IDDISTRIBUIDOR BIGINT,
    IDTIPOPEDIDO BIGINT,
    ESTADO VARCHAR(15),
    TOTALIMPORTE DOUBLE NOT NULL,
    IDUSUARIO BIGINT,
    VALORDESCUENTO DOUBLE NOT NULL,
    VALORRETENCION DOUBLE
);
CREATE TABLE persona
(
    IDPERSONA BIGINT PRIMARY KEY NOT NULL,
    AM VARCHAR(255),
    AP VARCHAR(255),
    CEM_COD VARCHAR(255),
    EST_CIVIL VARCHAR(255),
    FECHA_NAC DATE,
    NOM VARCHAR(255),
    NRO_DOC VARCHAR(255),
    OCU_COD VARCHAR(255),
    SEXO VARCHAR(255),
    SIS_COD VARCHAR(255),
    TDO_COD VARCHAR(255),
    TIPO_PERSONA VARCHAR(45),
    DIRECCION VARCHAR(100),
    TELEFONO VARCHAR(15),
    NIT VARCHAR(20),
    CODIGOCLIENTE VARCHAR(10),
    RAZONSOCIAL VARCHAR(45),
    OBSERVACION VARCHAR(100),
    IDRETENCION BIGINT,
    IDTIPOCLIENTE BIGINT,
    IDDEPARTAMENTO BIGINT,
    descuento DOUBLE
);
CREATE TABLE promocion
(
    IDPROMOCION BIGINT PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(50),
    FECHAINICIO DATE,
    FECHAFIN DATE,
    ESTADO VARCHAR(15),
    TOTAL DOUBLE
);
CREATE TABLE retencion
(
    IDRETENCION BIGINT PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(255),
    PORCENTAGE DOUBLE,
    ESTADO BIT
);
CREATE TABLE rol
(
    IDROL BIGINT PRIMARY KEY NOT NULL,
    DESCRIPCION LONGTEXT,
    IDCOMPANIA BIGINT,
    NOMBRE VARCHAR(255),
    VERSION BIGINT
);
CREATE TABLE tipocliente
(
    IDTIPOCLIENTE BIGINT PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(255)
);
CREATE TABLE tipopedido
(
    IDTIPOPEDIDO BIGINT PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(255)
);
CREATE TABLE usuario
(
    IDUSUARIO BIGINT PRIMARY KEY NOT NULL,
    CLAVE VARCHAR(255),
    EMAIL VARCHAR(255),
    FECHACREACION DATETIME,
    NUMEROUSUARIO VARCHAR(255),
    USUARIO VARCHAR(255),
    USUARIOFINANZAS INT,
    VERSION BIGINT,
    IDCOMPANIA BIGINT
);
CREATE TABLE usuariorol
(
    IDROL BIGINT NOT NULL,
    IDUSUARIO BIGINT NOT NULL,
    PRIMARY KEY (IDROL, IDUSUARIO)
);
CREATE TABLE ventaarticulo
(
    IDVENTAARTICULO BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    PRECIO DOUBLE,
    NO_CIA VARCHAR(255),
    COD_ART VARCHAR(255),
    IDPAQUETE BIGINT
);
CREATE TABLE ventacliente
(
    IDVENTACLIENTE BIGINT PRIMARY KEY NOT NULL,
    PRECIOESPECIAL DOUBLE,
    IDVENTAARTICULO BIGINT NOT NULL,
    IDPERSONA BIGINT NOT NULL
);
ALTER TABLE articulos_pedido ADD FOREIGN KEY (COD_ART, NO_CIA) REFERENCES inv_articulos (COD_ART, NO_CIA);
ALTER TABLE articulos_pedido ADD FOREIGN KEY (IDPEDIDOS) REFERENCES pedidos (IDPEDIDOS);
CREATE INDEX ARTICULOS_PEDIDO_INV_ARTICULOS_FK_idx ON articulos_pedido (COD_ART, NO_CIA);
CREATE INDEX FK_ARTICULOS_PEDIDO_PEDIDOS_idx ON articulos_pedido (IDPEDIDOS);
ALTER TABLE derechoacceso ADD FOREIGN KEY (IDCOMPANIA, IDMODULO) REFERENCES modulocompania (IDCOMPANIA, IDMODULO);
ALTER TABLE derechoacceso ADD FOREIGN KEY (IDFUNCIONALIDAD) REFERENCES funcionalidad (IDFUNCIONALIDAD);
ALTER TABLE derechoacceso ADD FOREIGN KEY (IDROL) REFERENCES rol (IDROL);
CREATE INDEX FK_derechoacceso_IDCOMPANIA ON derechoacceso (IDCOMPANIA, IDMODULO);
CREATE INDEX FK_derechoacceso_IDFUNCIONALIDAD ON derechoacceso (IDFUNCIONALIDAD);
ALTER TABLE funcionalidad ADD FOREIGN KEY (IDMODULO) REFERENCES modulo (IDMODULO);
CREATE INDEX FK_funcionalidad_IDMODULO ON funcionalidad (IDMODULO);
CREATE UNIQUE INDEX GEN_NAME_UNIQUE ON id_gen (GEN_NAME);
ALTER TABLE impresionfactura ADD FOREIGN KEY (IDMOVIMIENTO) REFERENCES movimiento (IDMOVIMIENTO);
ALTER TABLE impresionfactura ADD FOREIGN KEY (IDDOSIFICACION) REFERENCES dosificacion (IDDOSIFICACION);
ALTER TABLE impresionfactura ADD FOREIGN KEY (IDUSUARIO) REFERENCES usuario (IDUSUARIO);
CREATE INDEX IMPRESIONFACTURA_dosificacion_idx ON impresionfactura (IDDOSIFICACION);
CREATE INDEX IMPRESIONFACTURA_MOVIMIENTO_FK ON impresionfactura (IDMOVIMIENTO);
CREATE INDEX IMPRESIONFACTURA_usuario_FK ON impresionfactura (IDUSUARIO);
ALTER TABLE inv_articulos ADD FOREIGN KEY (COD_GRU, NO_CIA) REFERENCES inv_grupos (COD_GRU, NO_CIA);
CREATE INDEX FK_inv_articulos_COD_GRU ON inv_articulos (COD_GRU, NO_CIA);
ALTER TABLE modulocompania ADD FOREIGN KEY (IDMODULO) REFERENCES modulo (IDMODULO);
CREATE INDEX FK_modulocompania_IDMODULO ON modulocompania (IDMODULO);
ALTER TABLE movimiento ADD FOREIGN KEY (IDPEDIDOS) REFERENCES pedidos (IDPEDIDOS);
CREATE INDEX MOVIMIENTO_pedidos_FK ON movimiento (IDPEDIDOS);
ALTER TABLE pedidos ADD FOREIGN KEY (ESTADO_PEDIDO) REFERENCES estado_pedidos (IDESTADOPEDIDO);
ALTER TABLE pedidos ADD FOREIGN KEY (IDDISTRIBUIDOR) REFERENCES persona (IDPERSONA);
ALTER TABLE pedidos ADD FOREIGN KEY (IDTIPOPEDIDO) REFERENCES tipopedido (IDTIPOPEDIDO);
ALTER TABLE pedidos ADD FOREIGN KEY (IDUSUARIO) REFERENCES usuario (IDUSUARIO);
ALTER TABLE pedidos ADD FOREIGN KEY (IDCLIENTE) REFERENCES persona (IDPERSONA);
CREATE INDEX fk_pedidos_cliente_idx ON pedidos (IDCLIENTE);
CREATE INDEX FK_pedidos_ESTADO_PEDIDO ON pedidos (ESTADO_PEDIDO);
CREATE INDEX FK_pedidos_IDDISTRIBUIDOR ON pedidos (IDDISTRIBUIDOR);
CREATE INDEX FK_pedidos_IDTIPOPEDIDO ON pedidos (IDTIPOPEDIDO);
CREATE INDEX FK_pedidos_usuario_idx ON pedidos (IDUSUARIO);
ALTER TABLE persona ADD FOREIGN KEY (IDDEPARTAMENTO) REFERENCES departamento (IDDEPARTAMENTO);
ALTER TABLE persona ADD FOREIGN KEY (IDRETENCION) REFERENCES retencion (IDRETENCION);
ALTER TABLE persona ADD FOREIGN KEY (IDTIPOCLIENTE) REFERENCES tipocliente (IDTIPOCLIENTE);
CREATE UNIQUE INDEX IDPERSONA_UNIQUE ON persona (IDPERSONA);
CREATE INDEX FK_PERSONAS_DEPARTAMENTO_idx ON persona (IDDEPARTAMENTO);
CREATE INDEX FK_PERSONAS_RETENCION_idx ON persona (IDRETENCION);
CREATE INDEX FK_PERSONAS_TIPOCLIENTE_idx ON persona (IDTIPOCLIENTE);
ALTER TABLE usuario ADD FOREIGN KEY (IDCOMPANIA) REFERENCES compania (IDCOMPANIA);
CREATE INDEX FK_usuario_IDCOMPANIA ON usuario (IDCOMPANIA);
ALTER TABLE usuariorol ADD FOREIGN KEY (IDROL) REFERENCES rol (IDROL);
ALTER TABLE usuariorol ADD FOREIGN KEY (IDUSUARIO) REFERENCES usuario (IDUSUARIO);
CREATE INDEX FK_usuariorol_IDUSUARIO ON usuariorol (IDUSUARIO);
ALTER TABLE ventaarticulo ADD FOREIGN KEY (COD_ART, NO_CIA) REFERENCES inv_articulos (COD_ART, NO_CIA);
ALTER TABLE ventaarticulo ADD FOREIGN KEY (IDPAQUETE) REFERENCES ventaarticulo (IDVENTAARTICULO);
CREATE INDEX FK_ventaarticulo_COD_ART ON ventaarticulo (COD_ART, NO_CIA);
CREATE INDEX FK_ventaarticulo_paquete_idx ON ventaarticulo (IDPAQUETE);
ALTER TABLE ventacliente ADD FOREIGN KEY (IDPERSONA) REFERENCES persona (IDPERSONA);
ALTER TABLE ventacliente ADD FOREIGN KEY (IDVENTAARTICULO) REFERENCES ventaarticulo (IDVENTAARTICULO);
CREATE INDEX VentaCliente_CLIENTE_FK ON ventacliente (IDPERSONA);
CREATE INDEX VentaCliente_VENTAARTICULO_FK ON ventacliente (IDVENTAARTICULO);
