CREATE TABLE SUCURSAL
  (
    IDSUCURSAL  BIGINT NOT NULL ,
    NOMBRE      VARCHAR (150) ,
    descripcion VARCHAR (30) ,
    CONSTRAINT SUCURSAL_PK PRIMARY KEY ( IDSUCURSAL )
  );
  
  ALTER TABLE dosificacion ADD IDSUCURSAL BIGINT(20) NULL;
  ALTER TABLE usuario ADD IDSUCURSAL BIGINT(20) NULL;
  ALTER TABLE pago ADD IDSUCURSAL BIGINT(20) NULL;
  ALTER TABLE pedidos ADD IDSUCURSAL BIGINT(20) NULL;
  ALTER TABLE ventadirecta ADD IDSUCURSAL BIGINT(20) NULL;
  