INSERT INTO eos.territoriotrabajo (IDTERRITORIOTRABAJO, NOMBRE, PAIS, DESCRIPCION, IDDISTRIBUIDOR, IDDEPARTAMENTO) VALUES (1, 'Punata', 'Bolivia', 'descripcion', 2, 1);
INSERT INTO eos.territoriotrabajo (IDTERRITORIOTRABAJO, NOMBRE, PAIS, DESCRIPCION, IDDISTRIBUIDOR, IDDEPARTAMENTO) VALUES (3, 'Cochabamba Central', 'Bolivia', '', 1, 1);
INSERT INTO eos.territoriotrabajo (IDTERRITORIOTRABAJO, NOMBRE, PAIS, DESCRIPCION, IDDISTRIBUIDOR, IDDEPARTAMENTO) VALUES (4, 'Vinto', 'Bolivia', '', 1, 1);
INSERT INTO eos.territoriotrabajo (IDTERRITORIOTRABAJO, NOMBRE, PAIS, DESCRIPCION, IDDISTRIBUIDOR, IDDEPARTAMENTO) VALUES (5, 'Quillacollo', 'Bolivia', 'nose', 14, 1);
