INSERT INTO eos.tipopedido (IDTIPOPEDIDO, NOMBRE) VALUES (1, 'PEDIDO');
INSERT INTO eos.tipopedido (IDTIPOPEDIDO, NOMBRE) VALUES (2, 'DEGUSACION');
INSERT INTO eos.tipopedido (IDTIPOPEDIDO, NOMBRE) VALUES (3, 'REFRIGERIO');
INSERT INTO eos.tipopedido (IDTIPOPEDIDO, NOMBRE) VALUES (4, 'REPOSICION');
