CREATE
  TABLE TIPODOC
  (
    IDTIPODOC   BIGINT(20) ,
    NOMBRE      VARCHAR (5) ,
    DESCRIPCION VARCHAR ,
    CONSTRAINT TIPODOC_PK PRIMARY KEY ( IDTIPODOC )
  );
  
  ALTER TABLE khipus.pedidos ADD TIENEFACTURA BOOLEAN NULL;
  ALTER TABLE khipus.movimiento ADD CODIGO_QR VARCHAR(100) NOT NULL;
  ALTER TABLE khipus.pago CHANGE monto pago DOUBLE;   
  UPDATE `pedidos` SET contabilizado = 0 ;